### ISSUE TITLE
کتابخانه به پروژه اضافه نمیشه

### ISSUE THREAD

**Issue by alirezarazavi** [soheil-mohammadi/PersianDatePicker#1]
سلام. ممنون بابت این کتابخونه
مشکل اینجاست که وقتی کتابخونه رو به فایل گریدل اضافه میکنم و سینک میکنم کتابخونه به پروژه اضافه نمیشه و نمیتونم از اون در پروژه استفاده کنم.
لطفا خودتون یکبار به این صورت تست کنید ببینید مشکل از کجاست.

**Comment by soheil-mohammadi** [comment]
jitapck سلام . متاسفانه مشکل از سمت       
بود
 jcenter  ظاهرا خیلی ها هم به این مشکل برخورد کردند ... اما بنده توی مخزن   
اپ کردم به محض تایید همینجا اطلاع رسانی میکنم ... بازم عذر میخوام

**Comment by soheil-mohammadi** [comment]
مشکل حل شد ، و کتابخانه در حال حاظر در مخزن 
center 
قرار گرفته ، آماده استفاده 👍
